### ISSUE TITLE
Getting error from async_browser.py

### ISSUE THREAD

**Issue by patrickelectric** [python-zeroconf/python-zeroconf#1158]
```shell
DEBUG:asyncio:Using selector: EpollSelector
Traceback (most recent call last):
  File "/home/patrick/git/blue/companion-docker/core/services/beacon/test2.py", line 104, in <module>
    loop.run_until_complete(runner.async_run())
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/patrick/git/blue/companion-docker/core/services/beacon/test2.py", line 59, in async_run
    self.aiozc = AsyncZeroconf(ip_version=ip_version)
  File "/home/patrick/.local/lib/python3.10/site-packages/zeroconf/asyncio.py", line 169, in __init__
    self.zeroconf = zc or Zeroconf(
  File "/home/patrick/.local/lib/python3.10/site-packages/zeroconf/_core.py", line 486, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
  File "/home/patrick/.local/lib/python3.10/site-packages/zeroconf/_utils/net.py", line 358, in create_sockets
    listen_socket = new_socket(ip_version=ip_version, apple_p2p=apple_p2p, bind_addr=('',))
  File "/home/patrick/.local/lib/python3.10/site-packages/zeroconf/_utils/net.py", line 248, in new_socket
    s.bind(bind_tup)
OSError: [Errno 98] Address already in use
```

**Comment by bdraco** [comment]
duplicate of #967
