### ISSUE TITLE
AssertionError when resolving a service without address specified.

### ISSUE THREAD

**Issue by gillima** [python-zeroconf/python-zeroconf#118]
I have a Zeroconf service on a device with multiple network interfaces. The service shall be available on all network interface, therefore I use the default Zeroconf instance and do not provide an address when registering the service:
```
    zc = Zeroconf()
    info = ServiceInfo('_test._tcp.local.', name='Test._test._tcp.local.', port=12345)
    zc.register_service(info=info)
```

The service is properly registered and can be browsed using `avahi-browse -rp _test._tcp.` or the browser example of zeroconf, but as soon as the service is resolved, the registered service throws an assertion due to the missing address:
```
    Exception in thread zeroconf-Engine:
    Traceback (most recent call last):
      File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
        self.run()
      File "C:\Program Files\Python36\lib\site-packages\zeroconf.py", line 1107, in run
        reader.handle_read(socket_)
      File "C:\Program Files\Python36\lib\site-packages\zeroconf.py", line 1156, in handle_read
        self.zc.handle_query(msg, _MDNS_ADDR, _MDNS_PORT)
      File "C:\Program Files\Python36\lib\site-packages\zeroconf.py", line 2004, in handle_query
        self.send(out, addr, port)
      File "C:\Program Files\Python36\lib\site-packages\zeroconf.py", line 2008, in send
        packet = out.packet()
      File "C:\Program Files\Python36\lib\site-packages\zeroconf.py", line 993, in packet
        overrun_additionals += self.write_record(additional, 0)
      File "C:\Program Files\Python36\lib\site-packages\zeroconf.py", line 961, in write_record
        record.write(self)
      File "C:\Program Files\Python36\lib\site-packages\zeroconf.py", line 477, in write
        out.write_string(self.address)
      File "C:\Program Files\Python36\lib\site-packages\zeroconf.py", line 867, in write_string
        assert isinstance(value, bytes)
    AssertionError
```

As a probably solution for the issue I did a modification on the Zeroconf.handle_query method and did not add the address to the response if the address is not set. I'm not the specialist for DNS records and don't know if there are disadvantages of this!

```
    def handle_query(self, msg, addr, port):
        ...
        if question.type == _TYPE_SRV:
            if service.address:  # only add address if one is specified
                out.add_additional_answer(DNSAddress(
                    service.server, _TYPE_A, _CLASS_IN | _CLASS_UNIQUE,
                    _DNS_TTL, service.address))
```

Used environment:
zeroconf 0.19.1, Ubuntu LTS Linux 4.4.0-83-generic x86_64, Python 3.5.2, avahi-browse 0.6.32-rc
zeroconf 0.19.1, Windows 7 Pro, Python 3.6.0, Bonjour 2.0.4.0

**Comment by bdraco** [comment]
This no longer blows up as we do not send records that do not exist anymore
