### ISSUE TITLE
build failure on armv7

### ISSUE THREAD

**Issue by david-geiger** [python-zeroconf/python-zeroconf#1372]
Hi,

On Mageia Cauldron python-zeroconf fails to build only on armv7 with:

`Using pip 24.0 from /usr/lib/python3.12/site-packages/pip (python 3.12)
Looking in links: /home/iurt/rpmbuild/BUILD/zeroconf-0.132.2/pyproject-wheeldir
ERROR: Could not find a version that satisfies the requirement zeroconf==0.132.2 (from versions: none)
ERROR: No matching distribution found for zeroconf==0.132.2
error: Bad exit status from /home/iurt/rpmbuild/tmp/rpm-tmp.5Vu1TQ (%install)`

Attached full build log:
[build.armv7hl.0.20240420100107.log](https://github.com/python-zeroconf/python-zeroconf/files/15048616/build.armv7hl.0.20240420100107.log)

**Comment by nicolargo** [comment]
Bug also confirmed on my side with the version zeroconf-0.132.2.tar.gz on Linux Alpine ARMv7:

```
#86 [linux/arm64 buildfull 1/1] RUN /venv-build/bin/python3.11 -m pip install --target="/venv/lib/python3.11/site-packages"     -r optional-requirements.txt
#86 373.8 Collecting zeroconf (from -r optional-requirements.txt (line 42))
#86 373.9   Downloading zeroconf-0.132.2.tar.gz (170 kB)
#86 373.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 170.7/170.7 kB 5.3 MB/s eta 0:00:00
#86 374.3   Installing build dependencies: started
#86 ...

#79 [linux/arm/v6 buildfull 1/1] RUN /venv-build/bin/python3.11 -m pip install --target="/venv/lib/python3.11/site-packages"     -r optional-requirements.txt
#79 399.7   Installing backend dependencies: finished with status 'error'
#79 399.9   error: subprocess-exited-with-error
#79 399.9   
#79 399.9   × pip subprocess to install backend dependencies did not run successfully.
#79 399.9   │ exit code: 1
#79 399.9   ╰─> [91 lines of output]
#79 399.9       Collecting cmake>=3.14
#79 399.9         Downloading cmake-3.29.2.tar.gz (30 kB)
#79 399.9         Installing build dependencies: started
#79 399.9         Installing build dependencies: finished with status 'done'
#79 399.9         Getting requirements to build wheel: started
#79 399.9         Getting requirements to build wheel: finished with status 'done'
#79 399.9         Installing backend dependencies: started
#79 399.9         Installing backend dependencies: finished with status 'error'
#79 399.9         error: subprocess-exited-with-error
#79 399.9       
#79 399.9         × pip subprocess to install backend dependencies did not run successfully.
#79 399.9         │ exit code: 2
#79 399.9         ╰─> [68 lines of output]
#79 399.9             Collecting cmake
#79 399.9               Using cached cmake-3.29.2.tar.gz (30 kB)
#79 399.9             ERROR: Exception:
#79 399.9             Traceback (most recent call last):
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
#79 399.9                 status = run_func(*args)
#79 399.9                          ^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
#79 399.9                 return func(self, options, args)
#79 399.9                        ^^^^^^^^^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
#79 399.9                 requirement_set = resolver.resolve(
#79 399.9                                   ^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
#79 399.9                 result = self._result = resolver.resolve(
#79 399.9                                         ^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
#79 399.9                 state = resolution.resolve(requirements, max_rounds=max_rounds)
#79 399.9                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
#79 399.9                 self._add_to_criteria(self.state.criteria, r, parent=None)
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
#79 399.9                 if not criterion.candidates:
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
#79 399.9                 return bool(self._sequence)
#79 399.9                        ^^^^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
#79 399.9                 return any(self)
#79 399.9                        ^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
#79 399.9                 return (c for c in iterator if id(c) not in self._incompatible_ids)
#79 399.9                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
#79 399.9                 candidate = func()
#79 399.9                             ^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 182, in _make_candidate_from_link
#79 399.9                 base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
#79 399.9                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 228, in _make_base_candidate_from_link
#79 399.9                 self._link_candidate_cache[link] = LinkCandidate(
#79 399.9                                                    ^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 290, in __init__
#79 399.9                 super().__init__(
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
#79 399.9                 self.dist = self._prepare()
#79 399.9                             ^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
#79 399.9                 dist = self._prepare_distribution()
#79 399.9                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 301, in _prepare_distribution
#79 399.9                 return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
#79 399.9                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 525, in prepare_linked_requirement
#79 399.9                 return self._prepare_linked_requirement(req, parallel_builds)
#79 399.9                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 640, in _prepare_linked_requirement
#79 399.9                 dist = _get_prepared_distribution(
#79 399.9                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 70, in _get_prepared_distribution
#79 399.9                 with build_tracker.track(req, tracker_id):
#79 399.9               File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
#79 399.9                 return next(self.gen)
#79 399.9                        ^^^^^^^^^^^^^^
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/build/build_tracker.py", line 137, in track
#79 399.9                 self.add(req, tracker_id)
#79 399.9               File "/venv-build/lib/python3.11/site-packages/pip/_internal/operations/build/build_tracker.py", line 103, in add
#79 399.9                 raise LookupError(message)
#79 399.9             LookupError: https://files.pythonhosted.org/packages/80/bf/4f9a9f754507992be28b985d1e9b17f93a2271106b5916a212efe1d65205/cmake-3.29.2.tar.gz (from https://pypi.org/simple/cmake/) (requires-python:>=3.7) is already being built: cmake>=3.14 from https://files.pythonhosted.org/packages/80/bf/4f9a9f754507992be28b985d1e9b17f93a2271106b5916a212efe1d65205/cmake-3.29.2.tar.gz
#79 399.9             [end of output]
#79 399.9       
#79 399.9         note: This error originates from a subprocess, and is likely not a problem with pip.
#79 399.9       error: subprocess-exited-with-error
#79 399.9       
#79 399.9       × pip subprocess to install backend dependencies did not run successfully.
#79 399.9       │ exit code: 2
#79 399.9       ╰─> See above for output.
#79 399.9       
#79 399.9       note: This error originates from a subprocess, and is likely not a problem with pip.
#79 399.9       [end of output]
#79 399.9   
#79 399.9   note: This error originates from a subprocess, and is likely not a problem with pip.
#79 399.9 error: subprocess-exited-with-error
#79 399.9 
#79 399.9 × pip subprocess to install backend dependencies did not run successfully.
#79 399.9 │ exit code: 1
#79 399.9 ╰─> See above for output.
#79 399.9 
#79 399.9 note: This error originates from a subprocess, and is likely not a problem with pip.
#79 ERROR: process "/bin/sh -c /venv-build/bin/python${PYTHON_VERSION} -m pip install --target=\"/venv/lib/python${PYTHON_VERSION}/site-packages\"     -r optional-requirements.txt" did not complete successfully: exit code: 1
```

**Comment by bdraco** [comment]
That looks like a problem install cmake

It seems to have built successful on piwheels https://www.piwheels.org/logs/0000/1173/8896.txt and Home Assistant also was able to create wheels for armv7l https://wheels.home-assistant.io/musllinux/zeroconf-0.132.2-cp312-cp312-musllinux_1_2_armv7l.whl
