### ISSUE TITLE
0.132.2: pytest warnings and call traces

### ISSUE THREAD

**Issue by kloczek** [python-zeroconf/python-zeroconf#1373]
I'm packaging your module as an rpm package so I'm using the typical PEP517 based build, install and test cycle used on building packages from non-root account.
- `python3 -sBm build -w --no-isolation`
- because I'm calling `build` with `--no-isolation` I'm using during all processes only locally installed modules
- install .whl file in </install/prefix> using `installer` module
- run pytest with $PYTHONPATH pointing to sitearch and sitelib inside </install/prefix>
- build is performed in env which is *`cut off from access to the public network`* (pytest is executed with `-m "not network"`)

<details>
<summary>Here is pytest output:</summary>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-zeroconf-0.132.2-2.fc37.x86_64/usr/lib64/python3.10/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-zeroconf-0.132.2-2.fc37.x86_64/usr/lib/python3.10/site-packages
+ /usr/bin/pytest -ra -m 'not network'
==================================================================================== test session starts ====================================================================================
platform linux -- Python 3.10.14, pytest-8.1.1, pluggy-1.4.0
rootdir: /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2
configfile: pyproject.toml
plugins: xdist-3.5.0, asyncio-0.23.6
asyncio: mode=strict
collected 297 items

tests/services/test_browser.py ..........................                                                                                                                             [  8%]
tests/services/test_info.py .............................                                                                                                                             [ 18%]
tests/services/test_registry.py .....                                                                                                                                                 [ 20%]
tests/services/test_types.py ....                                                                                                                                                     [ 21%]
tests/test_asyncio.py .............................                                                                                                                                   [ 31%]
tests/test_cache.py ................                                                                                                                                                  [ 36%]
tests/test_core.py ....s.................                                                                                                                                             [ 44%]
tests/test_dns.py ...........................                                                                                                                                         [ 53%]
tests/test_engine.py ..                                                                                                                                                               [ 53%]
tests/test_exceptions.py .........                                                                                                                                                    [ 56%]
tests/test_handlers.py ...............................                                                                                                                                [ 67%]
tests/test_history.py ..                                                                                                                                                              [ 68%]
tests/test_init.py .......                                                                                                                                                            [ 70%]
tests/test_listener.py ..                                                                                                                                                             [ 71%]
tests/test_logger.py .....                                                                                                                                                            [ 72%]
tests/test_protocol.py ..............................................                                                                                                                 [ 88%]
tests/test_services.py ...                                                                                                                                                            [ 89%]
tests/test_updates.py ..                                                                                                                                                              [ 89%]
tests/utils/test_asyncio.py .......                                                                                                                                                   [ 92%]
tests/utils/test_ipaddress.py ..                                                                                                                                                      [ 92%]
tests/utils/test_name.py .....                                                                                                                                                        [ 94%]
tests/utils/test_net.py ...........s....                                                                                                                                              [100%]

===================================================================================== warnings summary ======================================================================================
tests/services/test_browser.py: 6 warnings
tests/services/test_info.py: 3 warnings
tests/services/test_types.py: 1 warning
tests/test_asyncio.py: 3 warnings
tests/test_core.py: 5 warnings
tests/test_handlers.py: 7 warnings
tests/test_listener.py: 1 warning
tests/utils/test_asyncio.py: 2 warnings
tests/utils/test_net.py: 1 warning
  /usr/lib64/python3.10/asyncio/base_events.py:688: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
    _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/services/test_browser.py::test_service_browser_listeners_no_update_service
  /usr/lib/python3.10/site-packages/_pytest/threadexception.py:77: PytestUnhandledThreadExceptionWarning: Exception in thread zeroconf-ServiceBrowser-_hap._tcp-2012344

  Traceback (most recent call last):
    File "/usr/lib64/python3.10/threading.py", line 1016, in _bootstrap_inner
      self.run()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_services/browser.py", line 783, in run
      self._fire_service_state_changed_event(event)
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_services/browser.py", line 712, in _fire_service_state_changed_event
      self._service_state_changed.fire(
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_services/__init__.py", line 56, in fire
      h(**kwargs)
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_services/browser.py", line 290, in _on_change_dispatcher
      getattr(listener, _ON_CHANGE_DISPATCH[state_change])(zeroconf, service_type, name)
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_services/__init__.py", line 45, in update_service
      raise NotImplementedError()
  NotImplementedError

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/services/test_info.py::test_service_name_change_as_seen_ip_not_in_cache
  /usr/lib64/python3.10/ipaddress.py:1195: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    return int.from_bytes(map(cls._parse_octet, octets), 'big')
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/services/test_info.py::test_service_name_change_as_seen_ip_not_in_cache
  /usr/lib64/python3.10/ipaddress.py:1195: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    return int.from_bytes(map(cls._parse_octet, octets), 'big')
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/services/test_info.py::test_service_name_change_as_seen_ip_not_in_cache
tests/test_core.py::Framework::test_launch_and_close_v6_only
tests/test_handlers.py::test_future_answers_are_removed_on_send
  /usr/lib64/python3.10/asyncio/selector_events.py:710: ResourceWarning: unclosed transport <_SelectorDatagramTransport fd=13>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/services/test_info.py::test_service_name_change_as_seen_ip_not_in_cache
tests/test_core.py::Framework::test_launch_and_close_v6_only
tests/test_handlers.py::test_future_answers_are_removed_on_send
  /usr/lib64/python3.10/asyncio/selector_events.py:710: ResourceWarning: unclosed transport <_SelectorDatagramTransport fd=14>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_asyncio.py::test_async_with_sync_passed_in_closed_in_async
  /usr/lib/python3.10/site-packages/_pytest/unraisableexception.py:80: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f9b40825700>

  Traceback (most recent call last):
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 1402, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_engine.py", line 84, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_engine.py", line 104, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 1404, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.10/asyncio/selector_events.py", line 706, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 753, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 515, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_asyncio.py::test_sync_within_event_loop_executor
  /usr/lib64/python3.10/pathlib.py:594: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    drv, root, parts = self._parse_args(args)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_asyncio.py::test_sync_within_event_loop_executor
  /usr/lib64/python3.10/pathlib.py:594: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    drv, root, parts = self._parse_args(args)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_asyncio.py::test_sync_within_event_loop_executor
tests/test_core.py::test_event_loop_blocked
tests/test_handlers.py::test_qu_response
  /usr/lib64/python3.10/asyncio/selector_events.py:710: ResourceWarning: unclosed transport <_SelectorDatagramTransport closing fd=13>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::Framework::test_launch_and_close_v6_only
  /usr/lib64/python3.10/asyncio/events.py:80: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    self._context.run(self._callback, *self._args)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::Framework::test_launch_and_close_v6_only
  /usr/lib64/python3.10/asyncio/events.py:80: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    self._context.run(self._callback, *self._args)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_open_close_twice_from_async
  /usr/lib/python3.10/site-packages/_pytest/unraisableexception.py:80: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f9b40844f20>

  Traceback (most recent call last):
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 1402, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_engine.py", line 84, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_engine.py", line 104, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 1404, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.10/asyncio/selector_events.py", line 706, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 753, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 515, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_core.py::test_multiple_sync_instances_stared_from_async_close
  /usr/lib/python3.10/site-packages/_pytest/unraisableexception.py:80: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f9b40844120>

  Traceback (most recent call last):
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 1402, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_engine.py", line 84, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_engine.py", line 104, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 1404, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.10/asyncio/selector_events.py", line 706, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 753, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 515, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/inspect.py:2277: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/inspect.py:2277: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
tests/test_handlers.py::test_qu_response
  /usr/lib64/python3.10/asyncio/selector_events.py:710: ResourceWarning: unclosed transport <_SelectorDatagramTransport closing fd=15>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/inspect.py:2277: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/inspect.py:2277: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/inspect.py:2277: ResourceWarning: unclosed <socket.socket fd=17, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/inspect.py:2277: ResourceWarning: unclosed <socket.socket fd=27, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/inspect.py:2277: ResourceWarning: unclosed <socket.socket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/inspect.py:2277: ResourceWarning: unclosed <socket.socket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    return _signature_fromstr(cls, func, s, skip_bound_arg)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/asyncio/selector_events.py:710: ResourceWarning: unclosed transport <_SelectorDatagramTransport closing fd=17>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_core.py::test_event_loop_blocked
  /usr/lib64/python3.10/asyncio/selector_events.py:710: ResourceWarning: unclosed transport <_SelectorDatagramTransport closing fd=28>
    _warn(f"unclosed transport {self!r}", ResourceWarning, source=self)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_dns.py::test_dns_service_server_key
  /usr/lib64/python3.10/threading.py:1486: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    with _active_limbo_lock:
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_dns.py::test_dns_service_server_key
  /usr/lib64/python3.10/threading.py:1486: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    with _active_limbo_lock:
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_handlers.py::test_qu_response
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/tests/__init__.py:50: ResourceWarning: unclosed <socket.socket fd=13, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    asyncio.run_coroutine_threadsafe(_wait_for_response(), zc.loop).result()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_handlers.py::test_qu_response
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/tests/__init__.py:50: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    asyncio.run_coroutine_threadsafe(_wait_for_response(), zc.loop).result()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_handlers.py::test_qu_response
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/tests/__init__.py:50: ResourceWarning: unclosed <socket.socket fd=15, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 5353)>
    asyncio.run_coroutine_threadsafe(_wait_for_response(), zc.loop).result()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_handlers.py::test_qu_response
  /home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/tests/__init__.py:50: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    asyncio.run_coroutine_threadsafe(_wait_for_response(), zc.loop).result()
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/test_handlers.py::test_qu_response
  /usr/lib/python3.10/site-packages/_pytest/unraisableexception.py:80: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object AsyncEngine._async_setup at 0x7f9b40f73e60>

  Traceback (most recent call last):
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 1402, in create_datagram_endpoint
      await waiter
  GeneratorExit

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_engine.py", line 84, in _async_setup
      await self._async_create_endpoints()
    File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.132.2/src/zeroconf/_engine.py", line 104, in _async_create_endpoints
      transport, protocol = await loop.create_datagram_endpoint(
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 1404, in create_datagram_endpoint
      transport.close()
    File "/usr/lib64/python3.10/asyncio/selector_events.py", line 706, in close
      self._loop.call_soon(self._call_connection_lost, None)
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 753, in call_soon
      self._check_closed()
    File "/usr/lib64/python3.10/asyncio/base_events.py", line 515, in _check_closed
      raise RuntimeError('Event loop is closed')
  RuntimeError: Event loop is closed

    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

tests/test_handlers.py::test_future_answers_are_removed_on_send
  /usr/lib64/python3.10/unittest/mock.py:2181: ResourceWarning: unclosed <socket.socket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('127.0.0.1', 5353)>
    self.name = name
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

tests/utils/test_net.py::test_disable_ipv6_only_or_raise
  /usr/lib/python3.10/site-packages/_pytest/python.py:200: ResourceWarning: unclosed <socket.socket fd=16, family=AddressFamily.AF_INET, type=SocketKind.SOCK_DGRAM, proto=0, laddr=('0.0.0.0', 0)>
    result = testfunction(**testargs)
  Enable tracemalloc to get traceback where the object was allocated.
  See https://docs.pytest.org/en/stable/how-to/capture-warnings.html#resource-warnings for more info.

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
================================================================================== short test summary info ==================================================================================
SKIPPED [1] tests/test_core.py:112: apple_p2p happy path only testable on mac
SKIPPED [1] tests/utils/test_net.py:136: System has SO_REUSEPORT
================================================================== 295 passed, 2 skipped, 69 warnings in 118.73s (0:01:58) ==================================================================
```
</details>

<details>
<summary>List of installed modules in build env:</summary>

```console
Package                       Version
----------------------------- -----------
alabaster                     0.7.16
async-timeout                 4.0.3
Babel                         2.14.0
build                         1.2.1
charset-normalizer            3.3.2
Cython                        3.0.10
docutils                      0.20.1
exceptiongroup                1.1.3
execnet                       2.1.1
fastjsonschema                2.19.1
idna                          3.7
ifaddr                        0.2.0
imagesize                     1.4.1
importlib_metadata            7.1.0
iniconfig                     2.0.0
installer                     0.7.0
Jinja2                        3.1.3
lark                          1.1.9
MarkupSafe                    2.1.5
packaging                     24.0
pluggy                        1.4.0
poetry-core                   1.9.0
Pygments                      2.17.2
pyproject_hooks               1.0.0
pytest                        8.1.1
pytest-asyncio                0.23.6
pytest-xdist                  3.5.0
python-dateutil               2.9.0.post0
requests                      2.31.0
setuptools                    69.4.0
snowballstemmer               2.2.0
Sphinx                        7.2.6
sphinxcontrib-applehelp       1.0.8
sphinxcontrib-devhelp         1.0.6
sphinxcontrib-htmlhelp        2.0.5
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.7
sphinxcontrib-serializinghtml 1.1.10
tokenize_rt                   5.2.0
tomli                         2.0.1
urllib3                       2.2.1
wheel                         0.43.0
zipp                          3.18.1
```
</details>

Please let me know if you need more details or want me to perform some diagnostics.

**Comment by kloczek** [comment]
Forgot that I've already opened https://github.com/python-zeroconf/python-zeroconf/issues/1133
