### ISSUE TITLE
0.135.0: pep317 build fails

### ISSUE THREAD

**Issue by kloczek** [python-zeroconf/python-zeroconf#1417]
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
* Building wheel...
Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.135.0/setup.py", line 40, in <module>
    from build_ext import *
  File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.135.0/build_ext.py", line 51
    gdb_debug=True,
            ^
SyntaxError: ':' expected after dictionary key
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
    return _build_backend().build_wheel(wheel_directory, config_settings,
  File "/usr/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 58, in build_wheel
    return WheelBuilder.make_in(
  File "/usr/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 88, in make_in
    wb.build(target_dir=directory)
  File "/usr/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 121, in build
    self._build(zip_file)
  File "/usr/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 182, in _build
    self._run_build_command(setup)
  File "/usr/lib/python3.10/site-packages/poetry/core/masonry/builders/wheel.py", line 248, in _run_build_command
    subprocess.check_call([
  File "/usr/lib64/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.135.0/setup.py', 'build', '-b', '/home/tkloczko/rpmbuild/BUILD/python-zeroconf-

ERROR Backend subprocess exited when trying to invoke build_wheel
```

**Comment by bdraco** [comment]
@kloczek I think you have a patch that needs to be updated after https://github.com/python-zeroconf/python-zeroconf/commit/a43753f9249c78564ea23e77103cd74e9522e305#diff-8a22a3a4f9433fc58cdbea22a8c8f6751b9aa75d68b2545805d10052e7b8e22d
```
  File "/home/tkloczko/rpmbuild/BUILD/python-zeroconf-0.135.0/build_ext.py", line 51
    gdb_debug=True,
```

**Comment by bdraco** [comment]
Cannot reproduce
