### ISSUE TITLE
 ZeroConf() returns OSError: [Errno 48] Address already in use 

### ISSUE THREAD

**Issue by SudhindraAnegondhi** [python-zeroconf/python-zeroconf#967]
### Zeroconf() fails on instantiation with OSError: [Errno 48] Address already in use 

The code works perfectly well on _Ubuntu 21.04_ but fails with the following error on _macOS Big Sur version 11.5 :_
` ``csh
```
 File "/Users/sudhindra/projects/cloudphotoservice/browse.py", line 61, in <module>
    zeroconf = Zeroconf()
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_core.py", line 410, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_utils/net.py", line 360, in create_sockets
    respond_socket = new_respond_socket(i, apple_p2p=apple_p2p)
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_utils/net.py", line 319, in new_respond_socket
    respond_socket = new_socket(
  File "/usr/local/lib/python3.9/site-packages/zeroconf/_utils/net.py", line 244, in new_socket
    s.bind((bind_addr[0], port, *bind_addr[1:]))
OSError: [Errno 48] Address already in use
```

As you can see `Zeroconf()` just creates an instance of the Zeroconf class. Neither Port nor IP address has been specified.

**Comment by bdraco** [comment]
Can you post some more information about your network setup.

I'm able to use it on my m1 laptop without the error.

**Comment by probonopd** [comment]
Running into the same issue on FreeBSD.

```
from zeroconf import ServiceBrowser, Zeroconf, InterfaceChoice
import zeroconf

class MyListener:

    def remove_service(self, zeroconf, type, name):
        print("Service %s removed" % (name,))

    def add_service(self, zeroconf, type, name):
        info = zeroconf.get_service_info(type, name)
        print("Service %s added, service info: %s" % (name, info))

# zeroconf = Zeroconf()
# OSError: [Errno 48] Address already in use

zeroconf = Zeroconf(interfaces=["192.168.0.14"])
# Still getting
# OSError: [Errno 48] Address already in use

listener = MyListener()
browser = ServiceBrowser(zeroconf, "_http._tcp.local.", listener)

try:
    input("Press enter to exit...\n\n")
finally:
    zeroconf.close()
```

More information:

```
FreeBSD% uname -v
FreeBSD 12.2-RELEASE r366954 GENERIC

FreeBSD% ifconfig 
em0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> metric 0 mtu 1500
        options=81249b<RXCSUM,TXCSUM,VLAN_MTU,VLAN_HWTAGGING,VLAN_HWCSUM,LRO,WOL_MAGIC,VLAN_HWFILTER>
        ether ...
        inet6 ... prefixlen 64 scopeid 0x1
        inet6 ... prefixlen 64 autoconf
        inet 192.168.0.14 netmask 0xffffff00 broadcast 192.168.0.255
        media: Ethernet autoselect (100baseTX <full-duplex>)
        status: active
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
lo0: flags=8049<UP,LOOPBACK,RUNNING,MULTICAST> metric 0 mtu 16384
        options=680003<RXCSUM,TXCSUM,LINKSTATE,RXCSUM_IPV6,TXCSUM_IPV6>
        inet6 ::1 prefixlen 128
        inet6 fe80::1%lo0 prefixlen 64 scopeid 0x2
        inet 127.0.0.1 netmask 0xff000000
        groups: lo
        nd6 options=23<PERFORMNUD,ACCEPT_RTADV,AUTO_LINKLOCAL>
```

Is this related?

```
FreeBSD% hostname
FreeBSD

FreeBSD% ping FreeBSD       
ping: cannot resolve FreeBSD: Unknown host

FreeBSD% ping FreeBSD.local.
PING FreeBSD.local. (192.168.0.14): 56 data bytes
64 bytes from 192.168.0.14: icmp_seq=0 ttl=64 time=0.026 ms
```

```
>>> socket.gethostbyname(socket.gethostname())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno 4] Non-recoverable failure in name resolution
>>> socket.gethostname()
'FreeBSD'
```

**Comment by bdraco** [comment]
Can you try making the socket manually by calling https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/_utils/net.py#L214 and seeing where you hit the error?

**Comment by probonopd** [comment]
Thanks @bdraco - could you give me a concrete example on how to do this please?

**Comment by bdraco** [comment]
https://github.com/home-assistant/core/issues/56231

**Comment by bdraco** [comment]
Are you by chance running in docker or have a docker file that replicates the issue?

**Comment by tbec** [comment]
I had the same issue (macOS Big Sur 11.5.2) and was able to resolve the issue. The problem was indeed Apple's mDNS responder daemon. To fix the issue:

1. First disable System Integrity Protection
2. Unload the mDNSResponder daemon:
```
sudo launchctl unload /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
```
3. Enable to flag for `NoMulticastAdvertisements`:
```
sudo defaults write /Library/Preferences/com.apple.mDNSResponder.plist NoMulticastAdvertisements -bool true
```
4. Reload:
```
sudo launchctl load /System/Library/LaunchDaemons/com.apple.mDNSResponder.plist
```
5. Check that the flag is enabled:
```
sudo /usr/bin/defaults read /Library/Preferences/com.apple.mDNSResponder | /usr/bin/grep NoMulticastAdvertisements
```
Should return `1`.
6. Restart your computer. You should no longer see the port in use:
```
netstat -na | grep "5353"
```

Hope this helps someone.

**Comment by bdraco** [comment]
closed via #1028

**Comment by probonopd** [comment]
Still getting "Address already in use" when running the browsing example from the README on a machine on which Avahi is running.

**Comment by bdraco** [comment]
We only trap errno 49.  Looks like your system throws 48

**Comment by bdraco** [comment]
We could trap 48 as well but I don't think it will actually solve the issue as it's likely avahai is getting exclusive use of the port

**Comment by probonopd** [comment]
I'd be happy to test if you tell me how. Thanks!

**Comment by bdraco** [comment]
If you adjust this line to trap Errno 48 https://github.com/jstasiak/python-zeroconf/blob/master/zeroconf/_utils/net.py#L250 that should be a good test

**Comment by bdraco** [comment]
It should be `errno.EADDRINUSE` instead of `errno.EADDRNOTAVAIL`

**Comment by probonopd** [comment]
```
FreeBSD% sudo sed -i '' -e 's|errno.EADDRNOTAVAIL|errno.EADDRINUSE|g' /usr/local/lib/python3.8/site-packages/zeroconf/_utils/net.py

FreeBSD% python3 ~/Desktop/browse.py 
Traceback (most recent call last):
  File "/home/user/Desktop/browse.py", line 14, in <module>
    zeroconf = Zeroconf()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/_core.py", line 448, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 373, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
  File "/usr/local/lib/python3.8/site-packages/zeroconf/_utils/net.py", line 271, in add_multicast_member
    log.debug('Adding %r (socket %d) to multicast group', interface, listen_socket.fileno())
AttributeError: 'NoneType' object has no attribute 'fileno'
```

**Comment by bdraco** [comment]
It looks like its not going to be able to listen while avahai is running since its getting exclusive use of the socket unless we have the flags wrong for sharing the port for FreeBSD.  Unfortunately, I'm not a FreeBSD user so I can't comment on that.

**Comment by probonopd** [comment]
Does it work e.g., on Linux systems?

**Comment by swills** [comment]
> It looks like its not going to be able to listen while avahai is running since its getting exclusive use of the socket unless we have the flags wrong for sharing the port for FreeBSD. Unfortunately, I'm not a FreeBSD user so I can't comment on that.

I believe the code may not have the right flags. See:

https://www.freebsd.org/cgi/man.cgi?query=setsockopt&apropos=0&sektion=0&manpath=FreeBSD+13.0-RELEASE+and+Ports&arch=default&format=html

FWIW, one need not install FreeBSD in order to read it's documentation, but if you wish to do so for testing, it should be fairly easy to setup a VM:

https://download.freebsd.org/ftp/releases/VM-IMAGES/13.0-RELEASE/amd64/Latest/

**Comment by systemcrash** [comment]
I run into this now from time to time. I only see it because I cranked up logging defaults. 

I'm on macOS 10.15.7. Things seem to work out anyway, and stuff is advertised as expected.

**Comment by crees** [comment]
It appears to be undocumented, but FreeBSD does not allow reuse of ports by software running as a different user.  You can test this by running avahi-daemon with --no-drop-root and it'll suddenly start happily sharing the port.

If you want to use SO_REUSEPORT, all the binding software must run under the same UID.

**Comment by tjuerges** [comment]
> It appears to be undocumented, but FreeBSD does not allow reuse of ports by software running as a different user. You can test this by running avahi-daemon with --no-drop-root and it'll suddenly start happily sharing the port.
> 
> If you want to use SO_REUSEPORT, all the binding software must run under the same UID.

I can confirm that this is also true on macOS.

And sorry, but disabling a macOS system service is obviously not a solution but at most a temporary workaround until a proper solution has been implemented.

**Comment by vesper8** [comment]
Oh my... since I just lost 3 hours of my life dealing with this problem on MacOS 15.3, I thought I would share what was causing the issue in my case.

I had previously been able to use `PyChromecast` to cast media to my TV. Then a week ago I tried it and it wouldn't work anymore. Was getting `OSError: [Errno 48] Address already in use`

I found this issue and after enabling logging I saw that the port in question that was causing the issue was 5353

After running `sudo lsof -i :5353` I finally found the culprit! It was NoMachine. I installed NoMachine recently and it came with `nxserver` service that was using port 5353

I had to `sudo /etc/NX/nxserver --shutdown` and finally it solved this headache.
